* dotemacs
Minimalist emacs config. Uses the [[(https://github.com/raxod502/straight.el)][straight]] package manager.

** Setup
*** Dependency: Emacs
See ~Installing Emacs~ below.

*** Dependency: Fonts
Install [[https://github.com/tonsky/FiraCode][Fira Code]] for text and [[https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf][Inconsolata Nerd Font]] for modeline.

*** Dependency: LSP servers
**** Through ~lsp-install-server~

| Lang       | Available |
|------------+-----------|
| [[https://github.com/bash-lsp/bash-language-server][Bash]]       | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-dockerfile][Dockerfile]] | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-html][HTML]]       | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-css][CSS]]        | ✅        |

**** Clojure
Install ~clojure-lsp~ [[https://github.com/clojure-lsp/clojure-lsp/releases][manually]], and then sanity-check it:

#+BEGIN_SRC shell
# preferred
cp ~/Downloads/clojure-lsp /usr/local/bin/clojure-lsp

which clojure-lsp
# => /usr/local/bin/clojure-lsp

# on MacOS you might need to "allow" it through
# System Preferences -> Security & Privacy to get:
clojure-lsp --help
# => clojure-lsp <latest-release>
clj-kondo --help
# => clj-kondo <latest release>
#+END_SRC

**** Rust

Just make sure you have [[https://github.com/rust-analyzer/rust-analyzer][rust-analyzer]] installed.

*** Install
#+BEGIN_SRC bash
git clone https://github.com/kitallis/dotemacs.git ~/.emacs.d
#+END_SRC

On the first run, Emacs will install and compile any packages handled by the package manager.

Edit =~/.emacs.d/init-user.el= for small personal tweaks, since this file is gitignored and loaded last.

** Troubleshooting
When in doubt, bounce all your straight packages:

#+BEGIN_SRC bash
rm ~/.emacs.d/straight
#+END_SRC

If ~clojure-lsp~ or ~clj-kondo~ are behaving strangely, try:

#+BEGIN_SRC bash
# 1. upgrade clojure-lsp: https://github.com/clojure-lsp/clojure-lsp/releases/
# 2. upgrade clj-kondo: https://github.com/clj-kondo/clj-kondo/blob/master/doc/install.md#installation-script-macos-and-linux
# 3. clean caches:
cd $YOUR_PROJECT
rm .lsp/sqlite.db
rm -rf .clj-kondo/.cache/
# 4. prebuild clj-kondo cache:
mkdir .clj-kondo # if it doesn't exist
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs
# See: https://github.com/clj-kondo/clj-kondo#project-setup
#+END_SRC

** Maintenance
  - Straight / package manager configuration goes in ~init.el~
  - Configurations broadly categorized go in their own ~conf/*.el~ files
  - Run ~M-x straight-freeze-versions~ to keep the lockfile updated for all ~straight~ recipes

** Installing Emacs
**** OS X

Install vanilla Emacs as a Mac app from http://emacsformacosx.com. Other options, like Aquamacs, are supposed to make Emacs more “Mac-like,” but they’re problematic in the long run because they’re set up so differently from standard Emacs that it’s difficult to use the Emacs manual or follow along with tutorials.

**** Ubuntu

Follow the instructions at https://launchpad.net/~cassou/+archive/emacs.

**** Windows

You can find a binary at http://ftp.gnu.org/gnu/emacs/windows. After you download and unzip the latest version, you can run the Emacs executable under ~bin\runemacs.exe~.
