* dotemacs
Minimalist emacs config. Uses the [[(https://github.com/raxod502/straight.el)][straight]] package manager.

** Setup
*** Dependency: Emacs
See ~Installing Emacs~ below.

*** Dependency: Fonts
Install [[https://github.com/tonsky/FiraCode][Fira Code]] for text and [[https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf][Inconsolata Nerd Font]] for modeline.

*** Dependency: LSP servers
**** Through ~lsp-install-server~

| Lang       | Available |
|------------+-----------|
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-css/][Bash]]       | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-dockerfile/][Dockerfile]] | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-html/][HTML]]       | ✅        |
| [[https://emacs-lsp.github.io/lsp-mode/page/lsp-css/][CSS]]        | ✅        |

**** Clojure
Install ~clojure-lsp~ [[https://github.com/clojure-lsp/clojure-lsp#manually][manually]], and then sanity-check it:

#+BEGIN_SRC shell
# preferred
cp ~/Downloads/clojure-lsp /usr/local/bin/clojure-lsp

which clojure-lsp
# => /usr/local/bin/clojure-lsp

# on MacOS you might need to "allow" it through
# System Preferences -> Security & Privacy to get:
clojure-lsp --help
# => clojure-lsp 2021.02.11-12.43.06
#+END_SRC

**** Rust

Install [[https://github.com/rust-analyzer/rust-analyzer][rust-analyzer]].

*** Install
#+BEGIN_SRC bash
git clone https://github.com/kitallis/dotemacs.git ~/.emacs.d
#+END_SRC

On the first run, Emacs will install and compile any packages handled by the package manager.

Edit =~/.emacs.d/init-user.el= for small personal tweaks, since this file is gitignored and loaded last.

** Troubleshooting
When in doubt, bounce all your straight packages:

#+BEGIN_SRC bash
rm ~/.emacs.d/straight
#+END_SRC

** Maintenance
  - Straight / package manager configuration goes in ~init.el~
  - Configurations broadly categorized go in their own ~conf/*.el~ files
  - Customizations / overrides can go in ~init-user.el~ and are loaded last
  - Run ~M-x straight-freeze-versions~ to keep the lockfile updated for all ~straight~ recipes

** Installing Emacs
**** OS X

Install vanilla Emacs as a Mac app from http://emacsformacosx.com. Other options, like Aquamacs, are supposed to make Emacs more “Mac-like,” but they’re problematic in the long run because they’re set up so differently from standard Emacs that it’s difficult to use the Emacs manual or follow along with tutorials.

**** Ubuntu

Follow the instructions at https://launchpad.net/~cassou/+archive/emacs.

**** Windows

You can find a binary at http://ftp.gnu.org/gnu/emacs/windows. After you download and unzip the latest version, you can run the Emacs executable under ~bin\runemacs.exe~.
